### ISSUE TITLE
axes don't match array error when no segment object is detected via Python script

### ISSUE THREAD

**Issue by qizhen816** [triple-Mu/YOLOv8-TensorRT#119]
This is caused in [utils.py](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/models/utils.py#L108) when the `idx = scores > conf_thres` returns empty, the maskconf has a shape=0 dim.
however, the `cv2.resize` in [utils.py](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/models/utils.py#L126) is not safe as the mask is not in typical cv2 image shape.

**Comment by triple-Mu** [comment]
``` text
Traceback (most recent call last):
  File "/home/ubuntu/workspace/github/tripleMu/YOLOv8-TensorRT/infer-seg.py", line 106, in <module>
    main(args)
  File "/home/ubuntu/workspace/github/tripleMu/YOLOv8-TensorRT/infer-seg.py", line 43, in main
    bboxes, scores, labels, masks = seg_postprocess(
  File "/home/ubuntu/workspace/github/tripleMu/YOLOv8-TensorRT/models/torch_utils.py", line 28, in seg_postprocess
    masks = F.interpolate(masks[None],
  File "/home/ubuntu/miniconda3/envs/torch/lib/python3.8/site-packages/torch/nn/functional.py", line 3950, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 160, 160]
```
Sure! Let's fix it.

**Comment by triple-Mu** [comment]
How about know?
