### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by zohar-fzh** [triple-Mu/YOLOv8-TensorRT#134]
```
(track_venv) zox@a:~/Documents/track/yolov8_tensorrt$ python3 build.py --weights yolov8n.onnx --iou-thres 0.65 --conf-thres 0.25 --topk 100 --fp16  --device cuda:0
[08/03/2023-10:40:49] [TRT] [W] Unable to determine GPU memory usage
[08/03/2023-10:40:49] [TRT] [W] Unable to determine GPU memory usage
[08/03/2023-10:40:49] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "build.py", line 56, in <module>
    main(args)
  File "build.py", line 47, in main
    builder.build(fp16=args.fp16,
  File "/home/zox/Documents/track/yolov8_tensorrt/models/engine.py", line 75, in build
    self.__build_engine(fp16, input_shape, iou_thres, conf_thres, topk,
  File "/home/zox/Documents/track/yolov8_tensorrt/models/engine.py", line 42, in __build_engine
    builder = trt.Builder(logger)
TypeError: pybind11::init(): factory function returned nullptr

```

```
(track_venv) zox@a:~/Documents/track/yolov8_tensorrt$ nvidia-smi 
Thu Aug  3 10:45:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P0    N/A /  N/A |      9MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1311      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2161      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
(track_venv) zox@a:~/Documents/track/yolov8_tensorrt$ pip3 list | grep tensorrt
nvidia-tensorrt               99.0.0
tensorrt                      8.6.1
tensorrt-bindings             8.6.1
tensorrt-libs                 8.6.1
```

**Comment by zohar-fzh** [comment]
`pip3 uninstall nvidia-tensorrt` and `pip3 install nvidia-tensorrt==8.4.3.1` solved this

**Comment by willwang-cv** [comment]
thanks！
