### ISSUE TITLE
YOLOv8-pose Model with TensorRT

### ISSUE THREAD

**Issue by Edgar-Lzxc** [triple-Mu/YOLOv8-TensorRT#142]
[08/24/2023-13:26:11] [TRT] [E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
[08/24/2023-13:26:11] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "E:\AI\YOLOv8-TensorRT-main\infer-pose.py", line 112, in <module>
    main(args)
  File "E:\AI\YOLOv8-TensorRT-main\infer-pose.py", line 15, in main
    Engine = TRTModule(args.engine, device)
  File "E:\AI\YOLOv8-TensorRT-main\models\engine.py", line 218, in __init__
    self.__init_engine()
  File "E:\AI\YOLOv8-TensorRT-main\models\engine.py", line 227, in __init_engine
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

ultralytics               8.0.161
tensorrt                  8.4.3.1                  
torch                     2.0.0+cu117             
torchaudio                2.0.1+cu117             
torchvision               0.15.1+cu117

**Comment by triple-Mu** [comment]
If you convert onnx to engine by trtexec, make sure you install the python-tensorrt wheel in `TensorRT-xxxx.tar.gz`.
Do not use `pip install nvidia-tensorrt`.
