### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liautumn** [triple-Mu/YOLOv8-TensorRT#170]
Traceback (most recent call last):
  File "D:\autumn\Documents\JetBrainsProjects\PyCharm\YOLOv8-TensorRT-main\autumn\infer-det-my.py", line 65, in <module>
    detect(engine='D:\\autumn\\Documents\\JetBrainsProjects\\PyCharm\\YOLOv8-TensorRT-main\\autumn\\model\\yolov8n.engine',
  File "D:\autumn\Documents\JetBrainsProjects\PyCharm\YOLOv8-TensorRT-main\autumn\infer-det-my.py", line 38, in detect
    bboxes, scores, labels = det_postprocess(data)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\autumn\Documents\JetBrainsProjects\PyCharm\YOLOv8-TensorRT-main\models\torch_utils.py", line 63, in det_postprocess
    assert len(data) == 4
           ^^^^^^^^^^^^^^
AssertionError

**Comment by triple-Mu** [comment]
How do you get onnx?
Do you use `export-det.py`?

**Comment by liautumn** [comment]
> 你如何获得onnx？你用吗？`export-det.py`
Thanks, I exported it with yolo, no problem with export-det.py
