### ISSUE TITLE
How to inference with batch size > 1?

### ISSUE THREAD

**Issue by anidh** [triple-mu/YOLOv8-TensorRT#81]
Hi There,

I need to infer with a batch size of 2. I have exported the model to onnx format using the command - 

`yolo export model=best.pt format=onnx simplify=True opset=11 dynamic=True` 

This generates an onnx file with a batch size of **-1** . I need help in converting this onnx file to an engine file which can have a batch size of 2 as well as help in inferencing of this engine file.
I tried to generate the engine file directly from the ultralytics repo using the command

 `yolo export model=best.pt format=engine dynamic=True simplify=True opset=11` 

Then using this engine file with your repo gives the following error -

`Traceback (most recent call last):
  File "/home/anidhsingh/YOLOv8-TensorRT/batch.py", line 87, in <module>
    main(args)
  File "/home/anidhsingh/YOLOv8-TensorRT/batch.py", line 44, in main
    bboxes, scores, labels = det_postprocess(data)
  File "/home/anidhsingh/YOLOv8-TensorRT/models/torch_utils.py", line 37, in det_postprocess
    assert len(data) == 4
AssertionError
`

Can you help infer with a batch size of 2 and how to generate the engine file for that? Thanks again for the great work on this repo.

**Comment by 1224wxwx** [comment]
same question.

**Comment by triple-Mu** [comment]
> same question.

Great I will add batch inference soon.

**Comment by AnaRhisT94** [comment]
Have you added batch inference? @triple-Mu

**Comment by Egorundel** [comment]
Have you added batch inference? @triple-Mu

**Comment by triple-mu** [comment]
Both halves are covered now:

1. **Build a batched engine.** Either export a fixed batch (`yolo export model=best.pt format=onnx opset=11 simplify batch=2`, or for End2End `python export-det.py --weights best.pt --input-shape 2 3 640 640`) and build it; or keep your dynamic (`-1`) ONNX and build with an optimization profile:
   ```
   trtexec --onnx=best.onnx --saveEngine=best.engine --fp16 \
     --minShapes=images:1x3x640x640 --optShapes=images:2x3x640x640 --maxShapes=images:4x3x640x640
   ```
2. **Run it.** `infer.py` now does batched inference (#317): it stacks a chunk of images into one `[N,3,H,W]` call and decodes per image. A fixed-batch engine runs at its own batch; a dynamic one follows `--batch N`. See the README "Batched inference" note and the [FAQ](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/docs/FAQ.md#inference).

Closing as resolved.
